### ISSUE TITLE
alpha value doesn't affect when using rotating 

### ISSUE THREAD

**Issue by Hosseinyzr** [kosinix/grafika#11]
when I rotate png images colored border will appear according to rotation angle.
now I can set the color but it cant be transparent and with no color.
$color=new Color('ffffff',0.0);
$editor->rotate($image,$rotation[$i],$color);

$color=new Color('ffffff',1.0);
$editor->rotate($image,$rotation[$i],$color);

both are equal!

![edited](https://cloud.githubusercontent.com/assets/18720898/26225085/c0cc0248-3c3a-11e7-95a6-9da6d7c9054b.png)

![original](https://cloud.githubusercontent.com/assets/18720898/26225016/61ed7f90-3c3a-11e7-8f20-daacc380183b.png)

**Comment by kosinix** [comment]
@Hosseinyzr have you had the chance to check if this is on Gd or Imagick?

**Comment by Hosseinyzr** [comment]
@kosinix  I think imagick is not installed... is this because of it?

**Comment by ivanfjz** [comment]
$color->setAlpha(127);
