### ISSUE TITLE
How can rotate a image?

### ISSUE THREAD

**Issue by zxygithub** [kosinix/grafika#3]
hi,

I want to rotate a image by use follow code, but the result  is same,  the rotate image same with original image.  How worte this code?

Alex 

<?php
require_once './vendor/autoload.php';

use Grafika\Grafika;

$editor = Grafika::createEditor();
$editor->open( "./images/list_1.jpg" );
$editor->rotate(90);
$editor->save( "./images/list_1_rotate.jpg", null, 90 );
$editor->free();

**Comment by kosinix** [comment]
Hello Alex,

It was a bug. Please update to v1.2.1 to fix the issue. Your code is correct.
