### ISSUE TITLE
Flip-x and flip-y

### ISSUE THREAD

**Issue by smartcorestudio** [kosinix/grafika#5]
Excellert lib! The only notable thing missing here is horizontal and vertical flip
Like this http://image.intervention.io/api/flip or https://github.com/claviska/SimpleImage#method-examples

**Comment by kosinix** [comment]
Thanks. Transformation api coming soon.  Stay tuned.

**Comment by kosinix** [comment]
@smartcorestudio Flip API now added. 

PS: You can now also resize animated GIFs even if you only have GD.
