### ISSUE TITLE
Error resize gif with GD

### ISSUE THREAD

**Issue by lemesdaniel** [kosinix/grafika#6]
I try resize a image and show error

Exception in GifHelper.php line 292:
Error decoding GIF.400 247256

the image: https://67.media.tumblr.com/tumblr_mbiqec1JUw1ri1mxoo1_400.gif

**Comment by kosinix** [comment]
@lemesdaniel,

Thank you for taking the time to report this. 

Its now fix on version 1.4.1.

Explanation: I left out support for **animated GIF with comments** and placed it on my to do list. I didnt expect to work on it this soon. but here we go :-)

Best

**Comment by lemesdaniel** [comment]
I'm sorry, I was just testing because I'm making a package for easy integration with laravel

**Comment by kosinix** [comment]
No problem. Its all good. Thank you for making the integration
