### ISSUE TITLE
Seems like crop is adding the x and y offsets twice?

### ISSUE THREAD

**Issue by HsRealDev** [kosinix/grafika#7]
I t seems that in Grafika/Imagick/Editor.php lines 179 and 180 X and Y offsets are added to the $x and $y params. 

But it seems that the offsets are already added at Grafika/Position.php on lines 119 and 120 right? Those values are used to initialize $x and $y later in the first place.

So Grafika/Imagick/Editor.php lines 179 and 180 can be just removed?

**Comment by kosinix** [comment]
Thank you for reporting. You are right. [Fixed](https://github.com/kosinix/grafika/commit/a758273f0de5a012a817115c3f24a43f6e4aaec5)
